"""sync user events

Revision ID: 3aa20e5cf12b
Revises: 4b57689ac703
Create Date: 2026-09-19 20:26:35.550504

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aa20e5cf12b'
down_revision: str | None = '4b57689ac703'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_events',
    sa.Column('event_id', sa.UUID(), nullable=False, comment='UUID v4 généré par le client (déduplication)'),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('xp_added', 'streak_day', name='user_event_kind'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True, comment='Valeur numérique (ex: XP gagnés). NULL si non applicable.'),
    sa.Column('reason', sa.String(length=100), nullable=True, comment="Raison métier (ex: 'quiz_passed', 'lesson_completed')"),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False, comment="Horodatage client de l'événement"),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('server_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_user_events_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_events')),
    sa.UniqueConstraint('student_id', 'event_id', name='uq_user_events_student_event'),
    comment='Journal CRDT additif (XP, streaks)'
    )
    op.create_index('ix_user_events_event_ts', 'user_events', ['event_ts'], unique=False)
    op.create_index('ix_user_events_student_kind', 'user_events', ['student_id', 'kind'], unique=False)
    op.add_column('student_profiles', sa.Column('last_streak_date', sa.Date(), nullable=True, comment='Dernière date à laquelle un streak a été compté (UTC)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'last_streak_date')
    op.drop_index('ix_user_events_student_kind', table_name='user_events')
    op.drop_index('ix_user_events_event_ts', table_name='user_events')
    op.drop_table('user_events')
    # ### end Alembic commands ###
