"""auth otp + trusted devices

Revision ID: 4b57689ac703
Revises: 71876a72c1dc
Create Date: 2026-09-19 18:45:26.062434

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b57689ac703'
down_revision: str | None = '71876a72c1dc'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='NULL si le phone est inconnu (anti-énumération)'),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.Enum('register', 'login', 'reset_password', name='otp_purpose'), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False, comment='HMAC-SHA256(code, SECRET_KEY+phone+purpose) hex'),
    sa.Column('channel', sa.Enum('whatsapp', 'sms', name='otp_channel'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otp_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes')),
    comment='Codes OTP à usage unique'
    )
    op.create_index('ix_otp_codes_expires_at', 'otp_codes', ['expires_at'], unique=False)
    op.create_index('ix_otp_codes_phone_purpose', 'otp_codes', ['phone', 'purpose'], unique=False)
    op.create_index('ix_otp_codes_user_id', 'otp_codes', ['user_id'], unique=False)
    op.create_table('trusted_devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 du token trusted device (jamais en clair)'),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trusted_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_devices')),
    sa.UniqueConstraint('token_hash', name='uq_trusted_devices_token_hash'),
    sa.UniqueConstraint('token_hash', name=op.f('uq_trusted_devices_token_hash')),
    comment='Appareils de confiance (skip OTP pendant 30j)'
    )
    op.create_index('ix_trusted_devices_expires_at', 'trusted_devices', ['expires_at'], unique=False)
    op.create_index('ix_trusted_devices_user_id', 'trusted_devices', ['user_id'], unique=False)
    op.create_unique_constraint('uq_level_series', 'level_series', ['level_id', 'series_id'])
    op.create_unique_constraint('uq_parent_student', 'parent_student', ['parent_id', 'student_id'])
    op.add_column('users', sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True, comment='NULL = numéro non vérifié. Renseigné après /verify-otp.'))
    op.create_foreign_key('fk_users_avatar_file_id', 'users', 'stored_files', ['avatar_file_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_avatar_file_id', 'users', type_='foreignkey')
    op.drop_column('users', 'phone_verified_at')
    op.drop_constraint('uq_parent_student', 'parent_student', type_='unique')
    op.drop_constraint('uq_level_series', 'level_series', type_='unique')
    op.drop_index('ix_trusted_devices_user_id', table_name='trusted_devices')
    op.drop_index('ix_trusted_devices_expires_at', table_name='trusted_devices')
    op.drop_table('trusted_devices')
    op.drop_index('ix_otp_codes_user_id', table_name='otp_codes')
    op.drop_index('ix_otp_codes_phone_purpose', table_name='otp_codes')
    op.drop_index('ix_otp_codes_expires_at', table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
