"""initial schema

Revision ID: 71876a72c1dc
Revises: 
Create Date: 2026-09-19 08:42:36.702719

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71876a72c1dc'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Nom du niveau (ex: 6ème, 2nde, Terminale)'),
    sa.Column('cycle', sa.Enum('college', 'lycee_moderne', 'lycee_technique', name='cycle'), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False, comment='Ordre dans la scolarité (6ème=1, Terminale=7)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_levels')),
    sa.UniqueConstraint('name', 'cycle', name='uq_levels_name_cycle'),
    comment='Niveaux scolaires (collège, lycée moderne, lycée technique)'
    )
    op.create_index(op.f('ix_levels_created_at'), 'levels', ['created_at'], unique=False)
    op.create_index('ix_levels_cycle', 'levels', ['cycle'], unique=False)
    op.create_table('national_calendar',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.Enum('rentree', 'examen', 'conge', 'resultat', 'autre', name='calendar_event_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True, comment="NULL pour les événements d'un seul jour"),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_national_calendar')),
    comment='Calendrier scolaire officiel du Togo'
    )
    op.create_index(op.f('ix_national_calendar_created_at'), 'national_calendar', ['created_at'], unique=False)
    op.create_index('ix_national_calendar_event_type', 'national_calendar', ['event_type'], unique=False)
    op.create_index('ix_national_calendar_start_date', 'national_calendar', ['start_date'], unique=False)
    op.create_table('plans',
    sa.Column('code', sa.Enum('freemium', 'pass_jour', 'pass_semaine', 'pass_mois', name='plan_type'), nullable=False, comment='Identifiant technique du forfait (freemium, pass_jour...)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Nom affiché (ex: 'Pass Jour')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Description courte affichée sur la carte du forfait'),
    sa.Column('price_fcfa', sa.Numeric(precision=10, scale=2), nullable=False, comment='Prix en FCFA (0 pour le freemium)'),
    sa.Column('duration_days', sa.Integer(), nullable=False, comment='Durée en jours (0 = illimité pour freemium)'),
    sa.Column('advantages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='Liste des avantages à afficher (JSONB)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment="Si FALSE, le forfait n'est plus proposé à l'achat"),
    sa.Column('order_index', sa.Integer(), nullable=False, comment="Ordre d'affichage dans l'app (croissant)"),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('code', name='uq_plans_code'),
    sa.UniqueConstraint('code', name=op.f('uq_plans_code')),
    comment='Catalogue des forfaits Mobile Money'
    )
    op.create_index(op.f('ix_plans_created_at'), 'plans', ['created_at'], unique=False)
    op.create_index('ix_plans_is_active_order_index', 'plans', ['is_active', 'order_index'], unique=False)
    op.create_table('series',
    sa.Column('code', sa.String(length=10), nullable=False, comment='Code officiel de la série (ex: A4, C, D, F1)'),
    sa.Column('name', sa.String(length=150), nullable=False, comment="Libellé complet (ex: 'Série A4 - Littéraire')"),
    sa.Column('cycle', sa.Enum('college', 'lycee_moderne', 'lycee_technique', name='cycle'), nullable=False, comment='Type de lycée concerné (moderne ou technique)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series')),
    sa.UniqueConstraint('code', 'cycle', name='uq_series_code_cycle'),
    comment='Séries du lycée togolais (générales et techniques)'
    )
    op.create_index(op.f('ix_series_created_at'), 'series', ['created_at'], unique=False)
    op.create_index('ix_series_cycle', 'series', ['cycle'], unique=False)
    op.create_table('subjects',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('cycle', sa.Enum('college', 'lycee_moderne', 'lycee_technique', name='cycle'), nullable=True, comment='Cycle concerné (NULL = matière transverse à tous les cycles)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('name', name='uq_subjects_name'),
    comment='Matières scolaires'
    )
    op.create_index(op.f('ix_subjects_created_at'), 'subjects', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Numéro de téléphone au format international (+228...)'),
    sa.Column('email', sa.String(length=150), nullable=True, comment="Email optionnel (les élèves n'en ont pas toujours)"),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hash Argon2id du mot de passe'),
    sa.Column('role', sa.Enum('student', 'parent', 'teacher', 'admin', name='user_role'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_file_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avatar_file_id'], ['stored_files.id'], name='fk_users_avatar_file_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    comment='Comptes utilisateurs (élèves, parents, enseignants, admins)'
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('chapters',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=True, comment='Série spécifique (NULL si chapitre commun à toutes les séries)'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False, comment="Ordre dans l'année scolaire (1, 2, 3...)"),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_chapters_level_id_levels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_chapters_series_id_series'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_chapters_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters')),
    sa.UniqueConstraint('level_id', 'subject_id', 'series_id', 'order_index', name='uq_chapters_level_subject_series_order'),
    comment='Chapitres du programme officiel togolais'
    )
    op.create_index(op.f('ix_chapters_created_at'), 'chapters', ['created_at'], unique=False)
    op.create_index('ix_chapters_level_id', 'chapters', ['level_id'], unique=False)
    op.create_index('ix_chapters_series_id', 'chapters', ['series_id'], unique=False)
    op.create_index('ix_chapters_subject_id', 'chapters', ['subject_id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.Enum('android', 'ios', 'web', name='platform'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_device_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_tokens')),
    sa.UniqueConstraint('fcm_token', name=op.f('uq_device_tokens_fcm_token')),
    comment='Jetons FCM par appareil utilisateur'
    )
    op.create_index(op.f('ix_device_tokens_created_at'), 'device_tokens', ['created_at'], unique=False)
    op.create_index('ix_device_tokens_user_id', 'device_tokens', ['user_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False, comment="Endpoint concerné (ex: 'sync:apply-event')"),
    sa.Column('key', sa.String(length=64), nullable=False, comment='UUID v4 fourni par le client (header ou body)'),
    sa.Column('request_hash', sa.String(length=64), nullable=False, comment='SHA-256 du body de la requête (détecte les abus de clé)'),
    sa.Column('response_status', sa.Integer(), nullable=False, comment='Code HTTP de la réponse originale (200, 201, 409...)'),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Body JSON de la réponse originale (rejoué tel quel)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment="Date d'expiration de la clé (TTL recommandé : 7 jours)"),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('user_id', 'scope', 'key', name='uq_idempotency_user_scope_key'),
    comment="Clés d'idempotence pour sync et télémétrie"
    )
    op.create_index('ix_idempotency_expires_at', 'idempotency_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_created_at'), 'idempotency_keys', ['created_at'], unique=False)
    op.create_table('level_series',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_level_series_level_id_levels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_level_series_series_id_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('level_id', 'series_id', name=op.f('pk_level_series')),
    sa.UniqueConstraint('level_id', 'series_id', name='uq_level_series'),
    comment='Séries disponibles par niveau (many-to-many)'
    )
    op.create_index('ix_level_series_series_id', 'level_series', ['series_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alerts_exam', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('alerts_study', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('alerts_news', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_notification_preferences')),
    comment='Préférences de notification par utilisateur'
    )
    op.create_index(op.f('ix_notification_preferences_created_at'), 'notification_preferences', ['created_at'], unique=False)
    op.create_table('parent_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True, comment='Profession (statistiques agrégées uniquement)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_parent_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_parent_profiles')),
    comment="Données spécifiques aux parents d'élèves"
    )
    op.create_table('parent_student',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_parent_student_parent_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_parent_student_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'student_id', name=op.f('pk_parent_student')),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student'),
    comment='Liaison parent ↔ élève (many-to-many)'
    )
    op.create_index('ix_parent_student_student_id', 'parent_student', ['student_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False, comment='Identifiant de la chaîne de tokens (un login = une famille)'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hexadécimal du refresh token (jamais en clair)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Date de révocation. NULL = token actif.'),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True, comment='Nouveau token issu de la rotation (chaînage)'),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    comment='Refresh tokens JWT avec rotation et détection de réutilisation'
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_family_id', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sent_notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('reminder', 'system', 'result', 'news', 'other', name='notification_type'), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sent_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sent_notifications')),
    comment='Historique des notifications envoyées aux utilisateurs'
    )
    op.create_index(op.f('ix_sent_notifications_created_at'), 'sent_notifications', ['created_at'], unique=False)
    op.create_index('ix_sent_notifications_is_read', 'sent_notifications', ['is_read'], unique=False)
    op.create_index('ix_sent_notifications_user_id_created_at', 'sent_notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('stored_files',
    sa.Column('uploader_id', sa.UUID(), nullable=True, comment='NULL si fichier système'),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Clé objet sur S3/MinIO/R2'),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('context', sa.Enum('avatar', 'resource_pdf', 'ai_scan', name='file_context'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_stored_files_uploader_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stored_files')),
    sa.UniqueConstraint('file_path', name='uq_stored_files_file_path'),
    sa.UniqueConstraint('file_path', name=op.f('uq_stored_files_file_path')),
    comment='Fichiers uploadés (avatars, PDF, scans IA)'
    )
    op.create_index('ix_stored_files_context', 'stored_files', ['context'], unique=False)
    op.create_index(op.f('ix_stored_files_created_at'), 'stored_files', ['created_at'], unique=False)
    op.create_index('ix_stored_files_uploader_id', 'stored_files', ['uploader_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=True, comment='Classe actuelle (ex: Terminale). Nullable si non renseigné.'),
    sa.Column('series_id', sa.UUID(), nullable=True, comment='Série du lycée (A4, C, D, F1...). NULL pour les collégiens.'),
    sa.Column('xp_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pairing_code', sa.String(length=6), nullable=False, comment="Code à 6 caractères permettant à un parent de s'abonner"),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_student_profiles_level_id_levels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_student_profiles_series_id_series'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_student_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_student_profiles')),
    comment='Données spécifiques aux élèves (niveau, série, gamification)'
    )
    op.create_index('ix_student_profiles_level_id', 'student_profiles', ['level_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_pairing_code'), 'student_profiles', ['pairing_code'], unique=True)
    op.create_index('ix_student_profiles_series_id', 'student_profiles', ['series_id'], unique=False)
    op.create_table('study_plannings',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.Enum('revision', 'exam', 'devoir', 'rentree', 'composition', 'homework', 'autre', name='planning_event_type'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_study_plannings_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plannings')),
    comment='Planning de révision personnel des élèves'
    )
    op.create_index(op.f('ix_study_plannings_created_at'), 'study_plannings', ['created_at'], unique=False)
    op.create_index('ix_study_plannings_is_completed', 'study_plannings', ['is_completed'], unique=False)
    op.create_index('ix_study_plannings_student_id_scheduled_date', 'study_plannings', ['student_id', 'scheduled_date'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False, comment='RESTRICT : un plan utilisé ne peut pas être supprimé'),
    sa.Column('plan_code', sa.String(length=50), nullable=False, comment='Snapshot dénormalisé du code du plan (audit)'),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True, comment='NULL pour le forfait freemium'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    comment='Abonnements Mobile Money des utilisateurs'
    )
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index('ix_subscriptions_end_date', 'subscriptions', ['end_date'], unique=False)
    op.create_index('ix_subscriptions_plan_id', 'subscriptions', ['plan_id'], unique=False)
    op.create_index('ix_subscriptions_user_id_is_active', 'subscriptions', ['user_id', 'is_active'], unique=False)
    op.create_table('teacher_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('school_name', sa.String(length=150), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='teacher_verification_status'), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_teacher_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_teacher_profiles')),
    comment='Données spécifiques aux enseignants (Marketplace V2)'
    )
    op.create_table('transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Montant en FCFA'),
    sa.Column('provider', sa.Enum('tmoney', 'flooz', 'card', 'cash', name='payment_provider'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='transaction_status'), server_default='pending', nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=False, comment="Référence de l'agrégateur (PayGate/CinetPay/FedaPay)"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('external_ref', name='uq_transactions_external_ref'),
    sa.UniqueConstraint('external_ref', name=op.f('uq_transactions_external_ref')),
    comment='Historique des paiements Mobile Money'
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index('ix_transactions_status', 'transactions', ['status'], unique=False)
    op.create_index('ix_transactions_user_id_created_at', 'transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True, comment='Contexte pédagogique optionnel'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_ai_conversations_chapter_id_chapters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_ai_conversations_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversations')),
    comment='Sessions de chat avec le Tuteur IA'
    )
    op.create_index('ix_ai_conversations_chapter_id', 'ai_conversations', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_created_at'), 'ai_conversations', ['created_at'], unique=False)
    op.create_index('ix_ai_conversations_student_id', 'ai_conversations', ['student_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_quizzes_chapter_id_chapters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_quizzes_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quizzes')),
    comment="Quiz d'entraînement générés par l'IA"
    )
    op.create_index('ix_quizzes_chapter_id', 'quizzes', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_quizzes_created_at'), 'quizzes', ['created_at'], unique=False)
    op.create_index('ix_quizzes_student_id', 'quizzes', ['student_id'], unique=False)
    op.create_table('resources',
    sa.Column('chapter_id', sa.UUID(), nullable=True, comment='NULL pour les annales générales (ex: sujet BAC toutes matières)'),
    sa.Column('type', sa.Enum('cours', 'exercice', 'annale', 'corrige', name='resource_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True, comment="Contenu Markdown directement lisible dans l'app (léger)"),
    sa.Column('file_id', sa.UUID(), nullable=True, comment='PDF rattaché (lourd, chargé à la demande)'),
    sa.Column('year', sa.Integer(), nullable=True, comment="Année d'édition (utile uniquement pour les annales)"),
    sa.Column('origin', sa.Enum('admin', 'teacher', 'ia', name='resource_origin'), server_default='admin', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_resources_chapter_id_chapters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['stored_files.id'], name=op.f('fk_resources_file_id_stored_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    comment='Ressources pédagogiques (cours, exercices, annales)'
    )
    op.create_index('ix_resources_chapter_id', 'resources', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_resources_created_at'), 'resources', ['created_at'], unique=False)
    op.create_index('ix_resources_origin', 'resources', ['origin'], unique=False)
    op.create_index('ix_resources_type_year', 'resources', ['type', 'year'], unique=False)
    op.create_table('study_fiches',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Structure : definitions / formules / erreurs_frequentes / resume'),
    sa.Column('source_file_id', sa.UUID(), nullable=True, comment='Photo du cahier source'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_study_fiches_chapter_id_chapters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_file_id'], ['stored_files.id'], name=op.f('fk_study_fiches_source_file_id_stored_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_study_fiches_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_fiches')),
    comment="Fiches de synthèse générées par l'IA"
    )
    op.create_index('ix_study_fiches_chapter_id', 'study_fiches', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_study_fiches_created_at'), 'study_fiches', ['created_at'], unique=False)
    op.create_index('ix_study_fiches_student_id', 'study_fiches', ['student_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='ai_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True, comment='Photo de cahier scannée jointe au message'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_messages_conversation_id_ai_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['stored_files.id'], name=op.f('fk_ai_messages_file_id_stored_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages')),
    comment='Messages des conversations IA (user/assistant/system)'
    )
    op.create_index('ix_ai_messages_conversation_id_created_at', 'ai_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_messages_created_at'), 'ai_messages', ['created_at'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_attempts_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_quiz_attempts_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempts')),
    comment='Historique des tentatives de quiz'
    )
    op.create_index(op.f('ix_quiz_attempts_completed_at'), 'quiz_attempts', ['completed_at'], unique=False)
    op.create_index('ix_quiz_attempts_quiz_id', 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index('ix_quiz_attempts_student_id', 'quiz_attempts', ['student_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Liste JSON des options, ex: ["1", "2", "3"]'),
    sa.Column('correct_answer', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True, comment="Explication IA en cas d'erreur"),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_questions_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_questions')),
    comment='Questions des quiz (QCM, Vrai/Faux, texte à trous)'
    )
    op.create_index(op.f('ix_quiz_questions_created_at'), 'quiz_questions', ['created_at'], unique=False)
    op.create_index('ix_quiz_questions_quiz_id', 'quiz_questions', ['quiz_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quiz_questions_quiz_id', table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_created_at'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index('ix_quiz_attempts_student_id', table_name='quiz_attempts')
    op.drop_index('ix_quiz_attempts_quiz_id', table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_completed_at'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_ai_messages_created_at'), table_name='ai_messages')
    op.drop_index('ix_ai_messages_conversation_id_created_at', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index('ix_study_fiches_student_id', table_name='study_fiches')
    op.drop_index(op.f('ix_study_fiches_created_at'), table_name='study_fiches')
    op.drop_index('ix_study_fiches_chapter_id', table_name='study_fiches')
    op.drop_table('study_fiches')
    op.drop_index('ix_resources_type_year', table_name='resources')
    op.drop_index('ix_resources_origin', table_name='resources')
    op.drop_index(op.f('ix_resources_created_at'), table_name='resources')
    op.drop_index('ix_resources_chapter_id', table_name='resources')
    op.drop_table('resources')
    op.drop_index('ix_quizzes_student_id', table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_created_at'), table_name='quizzes')
    op.drop_index('ix_quizzes_chapter_id', table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index('ix_ai_conversations_student_id', table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_created_at'), table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_chapter_id', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index('ix_transactions_user_id_created_at', table_name='transactions')
    op.drop_index('ix_transactions_status', table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('teacher_profiles')
    op.drop_index('ix_subscriptions_user_id_is_active', table_name='subscriptions')
    op.drop_index('ix_subscriptions_plan_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_end_date', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_study_plannings_student_id_scheduled_date', table_name='study_plannings')
    op.drop_index('ix_study_plannings_is_completed', table_name='study_plannings')
    op.drop_index(op.f('ix_study_plannings_created_at'), table_name='study_plannings')
    op.drop_table('study_plannings')
    op.drop_index('ix_student_profiles_series_id', table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_pairing_code'), table_name='student_profiles')
    op.drop_index('ix_student_profiles_level_id', table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index('ix_stored_files_uploader_id', table_name='stored_files')
    op.drop_index(op.f('ix_stored_files_created_at'), table_name='stored_files')
    op.drop_index('ix_stored_files_context', table_name='stored_files')
    op.drop_table('stored_files')
    op.drop_index('ix_sent_notifications_user_id_created_at', table_name='sent_notifications')
    op.drop_index('ix_sent_notifications_is_read', table_name='sent_notifications')
    op.drop_index(op.f('ix_sent_notifications_created_at'), table_name='sent_notifications')
    op.drop_table('sent_notifications')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_parent_student_student_id', table_name='parent_student')
    op.drop_table('parent_student')
    op.drop_table('parent_profiles')
    op.drop_index(op.f('ix_notification_preferences_created_at'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index('ix_level_series_series_id', table_name='level_series')
    op.drop_table('level_series')
    op.drop_index(op.f('ix_idempotency_keys_created_at'), table_name='idempotency_keys')
    op.drop_index('ix_idempotency_expires_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_device_tokens_user_id', table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_created_at'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index('ix_chapters_subject_id', table_name='chapters')
    op.drop_index('ix_chapters_series_id', table_name='chapters')
    op.drop_index('ix_chapters_level_id', table_name='chapters')
    op.drop_index(op.f('ix_chapters_created_at'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_created_at'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index('ix_series_cycle', table_name='series')
    op.drop_index(op.f('ix_series_created_at'), table_name='series')
    op.drop_table('series')
    op.drop_index('ix_plans_is_active_order_index', table_name='plans')
    op.drop_index(op.f('ix_plans_created_at'), table_name='plans')
    op.drop_table('plans')
    op.drop_index('ix_national_calendar_start_date', table_name='national_calendar')
    op.drop_index('ix_national_calendar_event_type', table_name='national_calendar')
    op.drop_index(op.f('ix_national_calendar_created_at'), table_name='national_calendar')
    op.drop_table('national_calendar')
    op.drop_index('ix_levels_cycle', table_name='levels')
    op.drop_index(op.f('ix_levels_created_at'), table_name='levels')
    op.drop_table('levels')
    # ### end Alembic commands ###
