"""user model complet

Revision ID: 8c9da99ef31c
Revises: cef827541e34
Create Date: 2026-09-14 17:19:08.750944

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c9da99ef31c'
down_revision: str | None = 'cef827541e34'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('cycle', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cycle IN ('college','lycee')", name=op.f('ck_levels_ck_niveaux_cycle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_levels'))
    )
    op.create_index(op.f('ix_levels_name'), 'levels', ['name'], unique=True)
    op.create_table('matters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matters'))
    )
    op.create_index(op.f('ix_matters_name'), 'matters', ['name'], unique=True)
    op.create_table('chapters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_chapters_level_id_levels')),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_chapters_matter_id_matters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters'))
    )
    op.create_index(op.f('ix_chapters_title'), 'chapters', ['title'], unique=True)
    op.create_table('level_matters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('level_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_level_matters_level_id_levels')),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_level_matters_matter_id_matters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_level_matters')),
    sa.UniqueConstraint('level_id', 'matter_id', name='uq_level_matter')
    )
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('profile_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('level_id', sa.UUID(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(op.f('fk_users_level_id_levels'), 'users', 'levels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_level_id_levels'), 'users', type_='foreignkey')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'level_id')
    op.drop_column('users', 'profile_url')
    op.drop_column('users', 'phone')
    op.drop_table('level_matters')
    op.drop_index(op.f('ix_chapters_title'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_matters_name'), table_name='matters')
    op.drop_table('matters')
    op.drop_index(op.f('ix_levels_name'), table_name='levels')
    op.drop_table('levels')
    # ### end Alembic commands ###
