"""uploads file status

Revision ID: aff9c75da48f
Revises: 3aa20e5cf12b
Create Date: 2026-09-19 21:48:19.612479

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff9c75da48f'
down_revision: str | None = '3aa20e5cf12b'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stored_files', sa.Column('status', sa.Enum('pending', 'uploaded', 'failed', name='file_status'), server_default='pending', nullable=False))
    op.add_column('stored_files', sa.Column('size_kb_declared', sa.Integer(), nullable=True, comment='Taille annoncée par le client au presign'))
    op.add_column('stored_files', sa.Column('size_kb_actual', sa.Integer(), nullable=True, comment='Taille réelle mesurée à la confirmation (head_object)'))
    op.add_column('stored_files', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stored_files', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment="Pour les fichiers pending : date d'expiration (purge ARQ)"))
    op.alter_column('stored_files', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               comment='Clé objet sur S3/MinIO/R2 (ex: avatars/{user_id}/{file_id}.webp)',
               existing_comment='Clé objet sur S3/MinIO/R2',
               existing_nullable=False)
    op.create_index('ix_stored_files_status_expires', 'stored_files', ['status', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stored_files_status_expires', table_name='stored_files')
    op.alter_column('stored_files', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               comment='Clé objet sur S3/MinIO/R2',
               existing_comment='Clé objet sur S3/MinIO/R2 (ex: avatars/{user_id}/{file_id}.webp)',
               existing_nullable=False)
    op.drop_column('stored_files', 'expires_at')
    op.drop_column('stored_files', 'uploaded_at')
    op.drop_column('stored_files', 'size_kb_actual')
    op.drop_column('stored_files', 'size_kb_declared')
    op.drop_column('stored_files', 'status')
    # ### end Alembic commands ###
